-- public.merchant
CREATE TABLE public.merchant (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	data_status_id int4 DEFAULT 1 NOT NULL,
	CONSTRAINT merchant_pkey PRIMARY KEY (id)
);


-- public."order" definition
CREATE TABLE public."order" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(50) NOT NULL,
	"date" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	status_id int4 NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	CONSTRAINT order_pkey PRIMARY KEY (id)
);


-- public."position" definition
CREATE TABLE public."position" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	data_status_id int4 DEFAULT 1 NOT NULL,
	CONSTRAINT position_pkey PRIMARY KEY (id)
);


-- public."role" definition
CREATE TABLE public."role" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	data_status_id int4 DEFAULT 1 NOT NULL,
	CONSTRAINT role_pkey PRIMARY KEY (id)
);

-- DROP TABLE public.menu;
CREATE TABLE public.menu (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	data_status_id int4 DEFAULT 1 NOT NULL,
	price int4 NOT NULL,
	merchant_id int8 NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	description varchar(200) NULL,
	code varchar(50) NULL,
	CONSTRAINT menu_pkey PRIMARY KEY (id),
	CONSTRAINT menu_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchant(id)
);


-- public.order_detail definition
CREATE TABLE public.order_detail (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	order_id int8 NOT NULL,
	user_id int8 NOT NULL,
	user_name varchar(100) NOT NULL,
	menu_id int8 NOT NULL,
	menu_name varchar(100) NOT NULL,
	price int4 NOT NULL,
	qty int4 NOT NULL,
	total int4 NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	CONSTRAINT order_detail_pkey PRIMARY KEY (id),
	CONSTRAINT order_detail_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."order"(id)
);


-- public.order_payment definition
CREATE TABLE public.order_payment (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	order_id int8 NOT NULL,
	user_id int8 NOT NULL,
	grand_total int4 NOT NULL,
	total_payment int4 NOT NULL,
	cashback int4 NOT NULL,
	payment_status_id int4 NOT NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	CONSTRAINT order_payment_pkey PRIMARY KEY (id),
	CONSTRAINT order_payment_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."order"(id)
);


-- public."user" definition
CREATE TABLE public."user" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	username varchar(100) NOT NULL,
	"password" varchar(100) NOT NULL,
	data_status_id int4 DEFAULT 1 NOT NULL,
	role_id int8 NOT NULL,
	position_id int8 NULL,
	created_by int8 DEFAULT 1 NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	modified_by int8 DEFAULT 1 NULL,
	modified_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NULL,
	email varchar(75) NULL,
	phone_number varchar(20) NULL,
	firebase_token varchar(250) NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT user_username_key UNIQUE (username),
	CONSTRAINT user_position_id_fkey FOREIGN KEY (position_id) REFERENCES public."position"(id),
	CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id) REFERENCES public."role"(id)
);


-- public.user_session definition
CREATE TABLE public.user_session (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	code varchar(10) NOT NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	is_valid bool DEFAULT true NOT NULL,
	CONSTRAINT user_session_pkey PRIMARY KEY (id),
	CONSTRAINT user_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id)
);
CREATE INDEX user_session_code_idx ON public.user_session USING btree (code);